import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import motor from "./../../assets/motor.png";
import clean from "./../../assets/clean.png";
import trasmition from "./../../assets/cambio.png";
import breakRepair from "./../../assets/break.png";
import oiel from "./../../assets/oil.png";
import pneu from "./../../assets/pneu.png";
import "./styles.css";
function Services() {
    return (_jsxs("div", { className: "container-services", children: [_jsx("h1", { className: "title", children: " N\u00F3s oferecemos os melhores servi\u00E7os de reparo. " }), _jsx("h4", { children: "Nossos servi\u00E7os" }), _jsxs("div", { className: "container-cards", children: [_jsxs("div", { className: "card", children: [_jsx("img", { src: oiel, alt: "Troca de \u00D3leo" }), _jsx("h3", { children: "Troca de \u00D3leo" }), _jsx("p", { children: "Servi\u00E7o especializado de troca de \u00F3leo, garantindo a lubrifica\u00E7\u00E3o adequada do motor e prolongando sua vida \u00FAtil." })] }), _jsxs("div", { className: "card", children: [_jsx("img", { src: breakRepair, alt: "Freios" }), _jsx("h3", { children: "Freios" }), _jsx("p", { children: "Manuten\u00E7\u00E3o e reparo do sistema de freios, garantindo seguran\u00E7a e efici\u00EAncia nas frenagens do ve\u00EDculo." })] }), _jsxs("div", { className: "card", children: [_jsx("img", { src: trasmition, alt: "C\u00E2mbio" }), _jsx("h3", { children: "C\u00E2mbio" }), _jsx("p", { children: "Revis\u00E3o e conserto do sistema de c\u00E2mbio, assegurando o correto funcionamento das marchas e suavidade nas trocas." })] }), _jsxs("div", { className: "card", children: [_jsx("img", { src: clean, alt: "Inje\u00E7\u00E3o Eletr\u00F4nica" }), _jsx("h3", { children: "Inje\u00E7\u00E3o Eletr\u00F4nica" }), _jsx("p", { children: "Especializa\u00E7\u00E3o em diagn\u00F3stico e reparo do sistema de inje\u00E7\u00E3o eletr\u00F4nica, otimizando o desempenho e consumo de combust\u00EDvel." })] }), _jsxs("div", { className: "card", children: [_jsx("img", { src: motor, alt: "Motores" }), _jsx("h3", { children: "Motores" }), _jsx("p", { children: "Manuten\u00E7\u00E3o e revis\u00E3o de motores, incluindo reparos, troca de pe\u00E7as e ajustes para garantir um funcionamento suave e eficiente." })] }), _jsxs("div", { className: "card", children: [_jsx("img", { src: pneu, alt: "Recarga de Bateria" }), _jsx("h3", { children: "Recarga de Bateria" }), _jsx("p", { children: "Servi\u00E7o de recarga e teste de bateria para garantir o pleno funcionamento do sistema el\u00E9trico do ve\u00EDculo." })] })] })] }));
}
export default Services;
